### ISSUE TITLE
段间距不固定

### ISSUE THREAD

**Issue by sunzhon** [nuaatug/nuaathesis#55]
段间距 不固定， 有的地方段间距是两行，很奇怪，或许latex自动放浮动体的时候，为了使得页面排满，请问该如何调整。
![11](https://user-images.githubusercontent.com/14144524/104258720-143b9a00-54bb-11eb-8296-a55359a5b320.png)

**Comment by phguo** [comment]
不知道 @sunzhon 咋解决的。我的解决方案是用 `\raggedbottom` 把空白留在每页最下边。

以下关于 `\raggedbottom` 的解释为 ChatGPT 生成。

In LaTeX, the command \raggedbottom is used for flexible page formatting. By default, LaTeX documents try to keep the same height for every page (except the last one) and stretches the vertical text spacing in order to achieve this. This can sometimes lead to irregular vertical spaces between lines or paragraphs, which may not always be desirable.

When you use the \raggedbottom command in the preamble of your LaTeX document, you're essentially telling LaTeX not to worry about maintaining the same page height. The text on each page is placed from the top of the page downwards, allowing variable page heights. The blank space, if any, is pushed towards the bottom of the page.
